<#
.SYNOPSIS
Compresses files or folders to Base64 text and restores them.

.DESCRIPTION
Creates an in-memory ZIP archive with the smallest available .NET compression level, writes it as Base64 text, splits oversized Base64 output into 25000-character text chunks, and can decode that Base64 text back into files. If OutputPath is omitted in Encode mode, the output is written under tmp/transfer so release/ remains reserved for the lightweight QS payload.

.PARAMETER Mode
Encode compresses InputPath and writes Base64 text to OutputPath. Decode reads Base64 text from InputPath and extracts it into OutputPath.

.PARAMETER InputPath
For Encode, a source file or folder. For Decode, a Base64 text file generated by Encode.

.PARAMETER OutputPath
For Encode, the destination Base64 text file or split-output manifest. If omitted, the tool writes tmp/transfer/<project-version>.txt under the repository root. For Decode, the destination folder for extracted files.

.PARAMETER ZipPath
Optional path for writing the intermediate ZIP bytes.

.PARAMETER Force
Allows existing output files to be overwritten.

.EXAMPLE
PS> .\src\tools\QuickSearch.TextTransfer.ps1 -Mode Encode -InputPath .\document.txt -Force

.EXAMPLE
PS> .\src\tools\QuickSearch.TextTransfer.ps1 -Mode Decode -InputPath .\payload.b64 -OutputPath .\restored -Force
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Encode', 'Decode')]
    [string]$Mode,

    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [string]$OutputPath,

    [string]$ZipPath,

    [switch]$Force
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Script:Base64ChunkCharacterLimit = 25000
$Script:SplitBase64ManifestFormat = 'QS.TextTransfer.SplitBase64.v1'

function Add-ZipCompressionAssemblies {
    Add-Type -AssemblyName System.IO.Compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem
}

function Get-BestZipCompressionLevel {
    $compressionLevelNames = [System.Enum]::GetNames([System.IO.Compression.CompressionLevel])
    if ($compressionLevelNames -contains 'SmallestSize') {
        return [System.Enum]::Parse([System.IO.Compression.CompressionLevel], 'SmallestSize')
    }

    return [System.IO.Compression.CompressionLevel]::Optimal
}

function Resolve-OutputFilePath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $parentPath = Split-Path -Parent $Path
    if ([string]::IsNullOrWhiteSpace($parentPath)) {
        return [System.IO.Path]::GetFullPath((Join-Path -Path (Get-Location).Path -ChildPath $Path))
    }

    return [System.IO.Path]::GetFullPath($Path)
}

function Get-QuickSearchRepoRoot {
    if ('tools' -eq (Split-Path -Leaf $PSScriptRoot)) {
        return (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
    }

    return (Split-Path -Parent $PSScriptRoot)
}

function Get-QuickSearchProjectVersion {
    $repoRoot = Get-QuickSearchRepoRoot
    $configPath = Join-Path -Path $repoRoot -ChildPath 'src\settings\config.json'
    if (Test-Path -LiteralPath $configPath) {
        try {
            $config = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
            if ($null -ne $config.Version -and -not [string]::IsNullOrWhiteSpace([string]$config.Version)) {
                return ([string]$config.Version).Trim()
            }
        }
        catch {
            Write-Host "Unable to read QS version from config: $configPath" -ForegroundColor Yellow
        }
    }

    $adcIndexPath = Join-Path -Path $repoRoot -ChildPath '.adc\index.md'
    if (Test-Path -LiteralPath $adcIndexPath) {
        $adcIndexContent = Get-Content -LiteralPath $adcIndexPath -Raw
        $versionMatch = [regex]::Match($adcIndexContent, '(?m)^version:\s*"?([^"\r\n]+)"?\s*$')
        if ($versionMatch.Success) {
            return $versionMatch.Groups[1].Value.Trim()
        }
    }

    return '0.0.0'
}

function Get-DefaultBase64OutputPath {
    $repoRoot = Get-QuickSearchRepoRoot
    $transferRoot = Join-Path -Path $repoRoot -ChildPath 'tmp\transfer'
    $version = Get-QuickSearchProjectVersion
    return (Join-Path -Path $transferRoot -ChildPath "$version.txt")
}

function Assert-SafeRelativeManifestPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path) -or [System.IO.Path]::IsPathRooted($Path) -or $Path.Contains(':')) {
        throw "Unsafe manifest chunk path: $Path"
    }

    foreach ($pathPart in @($Path -split '[\\/]')) {
        if ('.' -eq $pathPart -or '..' -eq $pathPart) {
            throw "Unsafe manifest chunk path: $Path"
        }
    }
}

function Remove-StaleSplitBase64Chunks {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ManifestPath
    )

    $manifestFullPath = Resolve-OutputFilePath $ManifestPath
    $manifestParentPath = Split-Path -Parent $manifestFullPath
    $manifestBaseName = [System.IO.Path]::GetFileNameWithoutExtension($manifestFullPath)
    $manifestExtension = [System.IO.Path]::GetExtension($manifestFullPath)
    if ([string]::IsNullOrWhiteSpace($manifestExtension)) {
        $manifestExtension = '.txt'
    }

    if (Test-Path -LiteralPath $manifestParentPath) {
        Get-ChildItem -LiteralPath $manifestParentPath -File -Filter "$manifestBaseName.part*$manifestExtension" |
            Remove-Item -Force
    }
}

function Get-SafeManifestChunkPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ManifestPath,

        [Parameter(Mandatory = $true)]
        [string]$ChunkPath
    )

    Assert-SafeRelativeManifestPath -Path $ChunkPath
    $manifestFolder = Split-Path -Parent (Resolve-OutputFilePath $ManifestPath)
    $candidatePath = [System.IO.Path]::GetFullPath((Join-Path -Path $manifestFolder -ChildPath $ChunkPath))
    $manifestFolderWithSeparator = [System.IO.Path]::GetFullPath($manifestFolder).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    if (-not $candidatePath.StartsWith($manifestFolderWithSeparator, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Manifest chunk path escapes the manifest folder: $ChunkPath"
    }

    return $candidatePath
}

function Write-Base64TransferOutput {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Base64Text,

        [Parameter(Mandatory = $true)]
        [string]$Base64OutputPath,

        [switch]$AllowOverwrite
    )

    $outputFullPath = Resolve-OutputFilePath $Base64OutputPath
    Assert-CanWriteFile -Path $outputFullPath -AllowOverwrite:$AllowOverwrite

    if ($Base64Text.Length -le $Script:Base64ChunkCharacterLimit) {
        Remove-StaleSplitBase64Chunks -ManifestPath $outputFullPath
        [System.IO.File]::WriteAllText($outputFullPath, $Base64Text, [System.Text.Encoding]::ASCII)
        return [PSCustomObject]@{ Path = $outputFullPath; Split = $false; ChunkCount = 0; ChunkPaths = @() }
    }

    Remove-StaleSplitBase64Chunks -ManifestPath $outputFullPath
    $outputParentPath = Split-Path -Parent $outputFullPath
    $outputBaseName = [System.IO.Path]::GetFileNameWithoutExtension($outputFullPath)
    $outputExtension = [System.IO.Path]::GetExtension($outputFullPath)
    if ([string]::IsNullOrWhiteSpace($outputExtension)) {
        $outputExtension = '.txt'
    }

    $chunkCount = [int][Math]::Ceiling($Base64Text.Length / $Script:Base64ChunkCharacterLimit)
    $chunkNames = @()
    for ($chunkIndex = 0; $chunkIndex -lt $chunkCount; $chunkIndex++) {
        $chunkName = ('{0}.part{1:D3}{2}' -f $outputBaseName, ($chunkIndex + 1), $outputExtension)
        $chunkPath = Join-Path -Path $outputParentPath -ChildPath $chunkName
        Assert-CanWriteFile -Path $chunkPath -AllowOverwrite:$AllowOverwrite
        $chunkNames += $chunkName
    }

    $chunkPaths = @()
    for ($chunkIndex = 0; $chunkIndex -lt $chunkCount; $chunkIndex++) {
        $chunkStart = $chunkIndex * $Script:Base64ChunkCharacterLimit
        $chunkLength = [Math]::Min($Script:Base64ChunkCharacterLimit, $Base64Text.Length - $chunkStart)
        $chunkText = $Base64Text.Substring($chunkStart, $chunkLength)
        $chunkPath = Join-Path -Path $outputParentPath -ChildPath $chunkNames[$chunkIndex]
        [System.IO.File]::WriteAllText($chunkPath, $chunkText, [System.Text.Encoding]::ASCII)
        $chunkPaths += $chunkPath
    }

    $manifest = [PSCustomObject]@{
        format = $Script:SplitBase64ManifestFormat
        encoding = 'ZipBase64'
        chunkSizeLimit = $Script:Base64ChunkCharacterLimit
        base64Characters = $Base64Text.Length
        chunkCount = $chunkCount
        chunks = $chunkNames
    }
    $manifestText = $manifest | ConvertTo-Json -Depth 5
    if ($manifestText.Length -gt $Script:Base64ChunkCharacterLimit) {
        throw "Split output manifest exceeds $Script:Base64ChunkCharacterLimit characters."
    }

    [System.IO.File]::WriteAllText($outputFullPath, $manifestText, [System.Text.Encoding]::ASCII)
    return [PSCustomObject]@{ Path = $outputFullPath; Split = $true; ChunkCount = $chunkCount; ChunkPaths = $chunkPaths }
}

function Read-Base64TransferInput {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Base64InputPath
    )

    $base64InputItem = Get-Item -LiteralPath $Base64InputPath
    $base64Text = [System.IO.File]::ReadAllText($base64InputItem.FullName)
    $trimmedText = $base64Text.TrimStart()
    if (-not $trimmedText.StartsWith('{')) {
        return (Get-NormalizedBase64Text -Base64Text $base64Text)
    }

    try {
        $manifest = $trimmedText | ConvertFrom-Json
    }
    catch {
        return (Get-NormalizedBase64Text -Base64Text $base64Text)
    }

    if ($manifest.format -ne $Script:SplitBase64ManifestFormat) {
        return (Get-NormalizedBase64Text -Base64Text $base64Text)
    }

    $builder = [System.Text.StringBuilder]::new()
    foreach ($chunkName in @($manifest.chunks)) {
        $chunkPath = Get-SafeManifestChunkPath -ManifestPath $base64InputItem.FullName -ChunkPath ([string]$chunkName)
        if (-not (Test-Path -LiteralPath $chunkPath)) {
            throw "Split Base64 chunk file not found: $chunkPath"
        }

        [void]$builder.Append((Get-NormalizedBase64Text -Base64Text ([System.IO.File]::ReadAllText($chunkPath))))
    }

    return $builder.ToString()
}

function Assert-CanWriteFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [switch]$AllowOverwrite
    )

    if (Test-Path -LiteralPath $Path) {
        $existingItem = Get-Item -LiteralPath $Path
        if ($existingItem.PSIsContainer) {
            throw "Output path is a directory, expected a file: $Path"
        }

        if (-not $AllowOverwrite) {
            throw "Output file already exists. Use -Force to overwrite: $Path"
        }
    }

    $parentPath = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($parentPath) -and -not (Test-Path -LiteralPath $parentPath)) {
        New-Item -ItemType Directory -Path $parentPath -Force | Out-Null
    }
}

function Get-RelativeArchivePath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RootPath,

        [Parameter(Mandatory = $true)]
        [string]$ChildPath
    )

    $rootFullPath = [System.IO.Path]::GetFullPath($RootPath).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $childFullPath = [System.IO.Path]::GetFullPath($ChildPath)

    if (-not $childFullPath.StartsWith($rootFullPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Path is outside the source root: $ChildPath"
    }

    return ($childFullPath.Substring($rootFullPath.Length).TrimStart([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar) -replace '\\', '/')
}

function Add-FileToZipArchive {
    param(
        [Parameter(Mandatory = $true)]
        [System.IO.Compression.ZipArchive]$ZipArchive,

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter(Mandatory = $true)]
        [string]$EntryName,

        [Parameter(Mandatory = $true)]
        [System.IO.Compression.CompressionLevel]$CompressionLevel
    )

    $fileInfo = Get-Item -LiteralPath $FilePath
    $zipEntry = $ZipArchive.CreateEntry($EntryName, $CompressionLevel)
    $zipEntry.LastWriteTime = [System.DateTimeOffset]::new($fileInfo.LastWriteTime)

    $entryStream = $zipEntry.Open()
    $fileStream = [System.IO.File]::Open($fileInfo.FullName, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
    try {
        $fileStream.CopyTo($entryStream)
    }
    finally {
        $fileStream.Dispose()
        $entryStream.Dispose()
    }
}

function New-ZipBytesFromPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath
    )

    if (-not (Test-Path -LiteralPath $SourcePath)) {
        throw "Input path not found: $SourcePath"
    }

    $sourceItem = Get-Item -LiteralPath $SourcePath
    $compressionLevel = Get-BestZipCompressionLevel
    $memoryStream = [System.IO.MemoryStream]::new()
    $zipArchive = [System.IO.Compression.ZipArchive]::new($memoryStream, [System.IO.Compression.ZipArchiveMode]::Create, $true)

    try {
        if ($sourceItem.PSIsContainer) {
            $sourceRoot = $sourceItem.FullName.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
            $sourceChildren = @(Get-ChildItem -LiteralPath $sourceRoot -Recurse -Force)

            foreach ($sourceChild in $sourceChildren) {
                $entryName = Get-RelativeArchivePath -RootPath $sourceRoot -ChildPath $sourceChild.FullName
                if ([string]::IsNullOrWhiteSpace($entryName)) {
                    continue
                }

                if ($sourceChild.PSIsContainer) {
                    $nestedChildren = @(Get-ChildItem -LiteralPath $sourceChild.FullName -Force)
                    if (0 -eq $nestedChildren.Count) {
                        [void]$zipArchive.CreateEntry("$entryName/")
                    }
                }
                else {
                    Add-FileToZipArchive -ZipArchive $zipArchive -FilePath $sourceChild.FullName -EntryName $entryName -CompressionLevel $compressionLevel
                }
            }
        }
        else {
            Add-FileToZipArchive -ZipArchive $zipArchive -FilePath $sourceItem.FullName -EntryName $sourceItem.Name -CompressionLevel $compressionLevel
        }
    }
    finally {
        $zipArchive.Dispose()
    }

    try {
        return $memoryStream.ToArray()
    }
    finally {
        $memoryStream.Dispose()
    }
}

function Get-NormalizedBase64Text {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Base64Text
    )

    return ($Base64Text -replace '\s+', '')
}

function Assert-SafeZipEntryName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$EntryName
    )

    if ([string]::IsNullOrWhiteSpace($EntryName)) {
        throw 'ZIP entry name cannot be empty.'
    }

    if ([System.IO.Path]::IsPathRooted($EntryName) -or $EntryName.Contains(':')) {
        throw "Unsafe ZIP entry name: $EntryName"
    }

    $entryParts = @($EntryName -split '[\\/]')
    foreach ($entryPart in $entryParts) {
        if ([string]::IsNullOrWhiteSpace($entryPart)) {
            continue
        }

        if ('.' -eq $entryPart -or '..' -eq $entryPart) {
            throw "Unsafe ZIP entry name: $EntryName"
        }
    }
}

function Get-SafeDestinationPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DestinationRoot,

        [Parameter(Mandatory = $true)]
        [string]$EntryName
    )

    Assert-SafeZipEntryName -EntryName $EntryName

    $normalizedEntryName = $EntryName -replace '/', [System.IO.Path]::DirectorySeparatorChar
    $destinationRootFullPath = [System.IO.Path]::GetFullPath($DestinationRoot)
    $destinationRootWithSeparator = $destinationRootFullPath.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    $destinationPath = [System.IO.Path]::GetFullPath((Join-Path -Path $destinationRootFullPath -ChildPath $normalizedEntryName))

    if (-not $destinationPath.StartsWith($destinationRootWithSeparator, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "ZIP entry would extract outside the destination folder: $EntryName"
    }

    return $destinationPath
}

function Expand-ZipBytesToFolder {
    param(
        [Parameter(Mandatory = $true)]
        [byte[]]$ZipBytes,

        [Parameter(Mandatory = $true)]
        [string]$DestinationPath,

        [switch]$AllowOverwrite
    )

    if (Test-Path -LiteralPath $DestinationPath) {
        $destinationItem = Get-Item -LiteralPath $DestinationPath
        if (-not $destinationItem.PSIsContainer) {
            throw "Output path is a file, expected a directory: $DestinationPath"
        }
    }
    else {
        New-Item -ItemType Directory -Path $DestinationPath -Force | Out-Null
    }

    $destinationRoot = (Get-Item -LiteralPath $DestinationPath).FullName
    $memoryStream = [System.IO.MemoryStream]::new($ZipBytes)
    $zipArchive = [System.IO.Compression.ZipArchive]::new($memoryStream, [System.IO.Compression.ZipArchiveMode]::Read)

    try {
        foreach ($zipEntry in $zipArchive.Entries) {
            $entryName = $zipEntry.FullName
            $destinationEntryPath = Get-SafeDestinationPath -DestinationRoot $destinationRoot -EntryName $entryName

            if ($entryName.EndsWith('/') -or $entryName.EndsWith('\')) {
                New-Item -ItemType Directory -Path $destinationEntryPath -Force | Out-Null
                continue
            }

            $destinationParentPath = Split-Path -Parent $destinationEntryPath
            if (-not (Test-Path -LiteralPath $destinationParentPath)) {
                New-Item -ItemType Directory -Path $destinationParentPath -Force | Out-Null
            }

            if ((Test-Path -LiteralPath $destinationEntryPath) -and -not $AllowOverwrite) {
                throw "Restored file already exists. Use -Force to overwrite: $destinationEntryPath"
            }

            $fileMode = [System.IO.FileMode]::CreateNew
            if ($AllowOverwrite) {
                $fileMode = [System.IO.FileMode]::Create
            }

            $entryStream = $zipEntry.Open()
            $outputStream = [System.IO.File]::Open($destinationEntryPath, $fileMode, [System.IO.FileAccess]::Write, [System.IO.FileShare]::None)
            try {
                $entryStream.CopyTo($outputStream)
            }
            finally {
                $outputStream.Dispose()
                $entryStream.Dispose()
            }

            if ($zipEntry.LastWriteTime.DateTime -gt [datetime]'1980-01-01') {
                [System.IO.File]::SetLastWriteTime($destinationEntryPath, $zipEntry.LastWriteTime.DateTime)
            }
        }
    }
    finally {
        $zipArchive.Dispose()
        $memoryStream.Dispose()
    }
}

function Invoke-EncodingMode {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath,

        [Parameter(Mandatory = $true)]
        [string]$Base64OutputPath,

        [string]$IntermediateZipPath,

        [switch]$AllowOverwrite
    )

    Assert-CanWriteFile -Path $Base64OutputPath -AllowOverwrite:$AllowOverwrite
    if (-not [string]::IsNullOrWhiteSpace($IntermediateZipPath)) {
        Assert-CanWriteFile -Path $IntermediateZipPath -AllowOverwrite:$AllowOverwrite
    }

    $sourceItem = Get-Item -LiteralPath $SourcePath
    $zipBytes = New-ZipBytesFromPath -SourcePath $SourcePath
    $base64Text = [System.Convert]::ToBase64String($zipBytes)
    $base64Output = Write-Base64TransferOutput -Base64Text $base64Text -Base64OutputPath $Base64OutputPath -AllowOverwrite:$AllowOverwrite

    if (-not [string]::IsNullOrWhiteSpace($IntermediateZipPath)) {
        [System.IO.File]::WriteAllBytes((Resolve-OutputFilePath $IntermediateZipPath), $zipBytes)
    }

    $sourceBytes = 0L
    if ($sourceItem.PSIsContainer) {
        $sourceFiles = @(Get-ChildItem -LiteralPath $sourceItem.FullName -Recurse -File -Force)
        foreach ($sourceFile in $sourceFiles) {
            $sourceBytes += $sourceFile.Length
        }
    }
    else {
        $sourceBytes = $sourceItem.Length
    }

    return [PSCustomObject]@{
        Mode = 'Encode'
        SourcePath = $sourceItem.FullName
        Base64OutputPath = $base64Output.Path
        ZipPath = if ([string]::IsNullOrWhiteSpace($IntermediateZipPath)) { $null } else { Resolve-OutputFilePath $IntermediateZipPath }
        SourceBytes = $sourceBytes
        ZipBytes = $zipBytes.Length
        Base64Characters = $base64Text.Length
        Split = $base64Output.Split
        ChunkCount = $base64Output.ChunkCount
        ChunkPaths = $base64Output.ChunkPaths
    }
}

function Invoke-DecodingMode {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Base64InputPath,

        [Parameter(Mandatory = $true)]
        [string]$DestinationPath,

        [string]$IntermediateZipPath,

        [switch]$AllowOverwrite
    )

    if (-not (Test-Path -LiteralPath $Base64InputPath)) {
        throw "Input Base64 file not found: $Base64InputPath"
    }

    if (-not [string]::IsNullOrWhiteSpace($IntermediateZipPath)) {
        Assert-CanWriteFile -Path $IntermediateZipPath -AllowOverwrite:$AllowOverwrite
    }

    $base64InputItem = Get-Item -LiteralPath $Base64InputPath
    $normalizedBase64Text = Read-Base64TransferInput -Base64InputPath $base64InputItem.FullName
    $zipBytes = [System.Convert]::FromBase64String($normalizedBase64Text)

    if (-not [string]::IsNullOrWhiteSpace($IntermediateZipPath)) {
        [System.IO.File]::WriteAllBytes((Resolve-OutputFilePath $IntermediateZipPath), $zipBytes)
    }

    Expand-ZipBytesToFolder -ZipBytes $zipBytes -DestinationPath $DestinationPath -AllowOverwrite:$AllowOverwrite

    return [PSCustomObject]@{
        Mode = 'Decode'
        Base64InputPath = $base64InputItem.FullName
        DestinationPath = (Get-Item -LiteralPath $DestinationPath).FullName
        ZipPath = if ([string]::IsNullOrWhiteSpace($IntermediateZipPath)) { $null } else { Resolve-OutputFilePath $IntermediateZipPath }
        Base64Characters = $normalizedBase64Text.Length
        ZipBytes = $zipBytes.Length
    }
}

Add-ZipCompressionAssemblies

if ('Encode' -eq $Mode) {
    $base64OutputPath = $OutputPath
    if ([string]::IsNullOrWhiteSpace($base64OutputPath)) {
        $base64OutputPath = Get-DefaultBase64OutputPath
    }

    Invoke-EncodingMode -SourcePath $InputPath -Base64OutputPath $base64OutputPath -IntermediateZipPath $ZipPath -AllowOverwrite:$Force
}
else {
    if ([string]::IsNullOrWhiteSpace($OutputPath)) {
        throw 'OutputPath is required in Decode mode.'
    }

    Invoke-DecodingMode -Base64InputPath $InputPath -DestinationPath $OutputPath -IntermediateZipPath $ZipPath -AllowOverwrite:$Force
}